### PR TITLE
Change default duration back to 1 hour

### PR DESCRIPTION
**Pull request by ejholmes**
Ever since upgrading to 0.3.0, I felt like my temporary credentials would expire a lot faster. Turns out the default expiration in the AssumeRoleProvider in the AWS SDK for Go is [15 minutes](https://github.com/aws/aws-sdk-go/blob/1dc0171900ca37b76031153546f388b9beaf07c1/aws/credentials/stscreds/assume_role_provider.go#L121), however we used to default to 1 hour.

This changes the default duration back to 1 hour, and also adds a flag to make it configurable.

### CODE REVIEW

**Review by phobologic — APPROVED** [review]

**Comment by ghost** [comment]
👍

**Comment by Photon0gen** [comment]
Any ETA on when this will get released?

**Comment by ejholmes** [comment]
Woops. Forgot about this. I'll merge and cut a new release.

**Comment by ejholmes** [comment]
https://github.com/remind101/assume-role/releases/tag/0.3.1

**Pull request merged**
