### PR TITLE
Use AWS API instead of CLI

### LINKED ISSUE #8: Use AWS API instead of CLI
Using the AWS go SDK (https://docs.aws.amazon.com/sdk-for-go/api/service/sts/) would make `assume-role` a self-contained binary instead of depending on the `aws` CLI.  Not urgent, the CLI is easy to installl; mostly interested if there's any reason why you prefer using the CLI instead of the SDK.

### PR DESCRIPTION
**Pull request by spaceshaker**
My first ever go-lang commit. Feel free to be harsh. :)

Fix #8

### CODE REVIEW

**Comment by ejholmes** [comment]
Thanks @spaceshaker! It was missing some vendored deps, but I fixed those up and pulled this in with 7370bd4e1b8cc2b69931c79a0c958306c4f3a5a6. I'll cut a new release today.

**Comment by spaceshaker** [comment]
HA. Ya, I guess it was missing a lot of vendored deps. How did you add those? Dependencies in Go seem like dark magic to me. I used the govendor tool to pull in the SDK as I did, clearly it didn't pull in nearly enough. I guess it worked because the SDK was in my $GOPATH?

Just wondering if you could let me know how you resolved this so I learn. :)

**Comment by ejholmes** [comment]
Yeah, vendoring in Go is a major pain. I usually do the following with govendor:

```console
$ govendor add +e # Add any "external" packages to vendor/
$ git add -f vendor/github.com # Ensure that the vendored deps get commited
```

**Comment by spaceshaker** [comment]
Thanks @ejholmes. FWIW I am going to create a new tools called `assume-role-saml` that borrows heavily from the approach (and code) you've taken here but which authenticates using a SAML IdP. This `assume-role` tool has turned out to be incredibly useful but my organization is moving away from IAM users toward 100% federated identities and as such I would like to create a tool that works similar to this one but for SAML-based role assumption.

**Comment by ejholmes** [comment]
@spaceshaker that sounds great. Our plan is also to move to SAML (we're federated, but from a single "Ops" aws account) once we get an IdP that doesn't suck (cough, Onelogin).

**Pull request merged**
