### PR TITLE
update go modules, including AWS SDK for Go for v1.38 so it supports SSO

### PR DESCRIPTION
**Pull request by anherrera**
I needed this tool to support AWS SSO profiles, which isn't supported until the AWS SDK for Go v1 version 1.37. 

I was going to use govendor and generate a new modules json file but the tool itself says to not use it. So I used go modules instead.

### CODE REVIEW

**Comment by anherrera** [comment]
Any feedback? I'd like to continue using this tool in my team without having to maintain a fork :)

**Comment by ivanmartos** [comment]
@anherrera did you please release your own version somewhere?

**Comment by anherrera** [comment]
I have not distributed another release of this publically, no. Just recompiled and had my team use it.

**Comment by rojosinalma** [comment]
I strongly suggest you do if you can/want. This project is long dead, from the maintenance point of view.

**Pull request closed without merging**
